export const UPDATE_SURVEY_CONFIGURATION =
  "creation/UPDATE_SURVEY_CONFIGURATION";
export type T_UPDATE_SURVEY_CONFIGURATION = typeof UPDATE_SURVEY_CONFIGURATION;

export const ADD_SURVEY_QUESTION = "creation/ADD_QUESTION";
export type T_ADD_SURVEY_QUESTION = typeof ADD_SURVEY_QUESTION;

export const REMOVE_SURVEY_QUESTION = "creation/REMOVE_QUESTION";
export type T_REMOVE_SURVEY_QUESTION = typeof REMOVE_SURVEY_QUESTION;

export const UPDATE_SURVEY_QUESTION = "creation/UPDATE_QUESTION";
export type T_UPDATE_SURVEY_QUESTION = typeof UPDATE_SURVEY_QUESTION;

export const UPDATE_SURVEY_COMPONENT_CONFIGURATION =
  "creation/UPDATE_COMPONENT_CONFIGURATION";
export type T_UPDATE_SURVEY_COMPONENT_CONFIGURATION =
  typeof UPDATE_SURVEY_COMPONENT_CONFIGURATION;

export const PUBLISH_SURVEY_REQUEST = "creation/PUBLISH_REQUEST";
export type T_PUBLISH_SURVEY_REQUEST = typeof PUBLISH_SURVEY_REQUEST;
