export const ADD_SURVEY_QUESTION = "creation/ADD_QUESTION";
export type T_ADD_SURVEY_QUESTION = typeof ADD_SURVEY_QUESTION;

export const UPDATE_SURVEY_QUESTION = "creation/UPDATE_QUESTION";
export type T_UPDATE_SURVEY_QUESTION = typeof UPDATE_SURVEY_QUESTION;

export const UPDATE_SURVEY_COMPONENT_CONFIGURATION =
  "creation/UPDATE_COMPONENT_CONFIGURATION";
export type T_UPDATE_SURVEY_COMPONENT_CONFIGURATION =
  typeof UPDATE_SURVEY_COMPONENT_CONFIGURATION;
