export const RETRIEVE_SURVEY_BY_ID = "submission/RETRIEVE_SURVEY_BY_ID";
export type T_RETRIEVE_SURVEY_BY_ID = typeof RETRIEVE_SURVEY_BY_ID;

export const RETRIEVE_SURVEY_BY_ID_SUCCESS =
  "submission/RETRIEVE_SURVEY_BY_ID_SUCCESS";
export type T_RETRIEVE_SURVEY_BY_ID_SUCCESS =
  typeof RETRIEVE_SURVEY_BY_ID_SUCCESS;

export const UPDATE_SURVEY_ANSWER = "submission/UPDATE_ANSWER";
export type T_UPDATE_SURVEY_ANSWER = typeof UPDATE_SURVEY_ANSWER;

export const SUBMIT_SURVEY_REQUEST = "submission/SUBMIT_REQUEST";
export type T_SUBMIT_SURVEY_REQUEST = typeof SUBMIT_SURVEY_REQUEST;
