export const LIST_OWNED_SURVEYS_REQUEST =
  "dashboard/LIST_OWNED_SURVEYS_REQUEST";
export type T_LIST_OWNED_SURVEYS_REQUEST = typeof LIST_OWNED_SURVEYS_REQUEST;

export const LIST_OWNED_SURVEYS_SUCCESS =
  "dashboard/LIST_OWNED_SURVEYS_SUCCESS";
export type T_LIST_OWNED_SURVEYS_SUCCESS = typeof LIST_OWNED_SURVEYS_SUCCESS;

export const SET_ACTIVE_SURVEY = "dashboard/SET_ACTIVE_SURVEY";
export type T_SET_ACTIVE_SURVEY = typeof SET_ACTIVE_SURVEY;

export const ACTIVE_SURVEY_RESULTS_REQUEST =
  "dashboard/ACTIVE_SURVEY_RESULTS_REQUEST";
export type T_ACTIVE_SURVEY_RESULTS_REQUEST =
  typeof ACTIVE_SURVEY_RESULTS_REQUEST;

export const ACTIVE_SURVEY_RESULTS_SUCCESS =
  "dashboard/ACTIVE_SURVEY_RESULTS_SUCCESS";
export type T_ACTIVE_SURVEY_RESULTS_SUCCESS =
  typeof ACTIVE_SURVEY_RESULTS_SUCCESS;
